# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'reactnativeyuntongdemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativeyuntongdemo
  pod 'yuntongxun-full-sdk', :path => '../../yuntongxun'

  target 'reactnativeyuntongdemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


